default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: <%= ENV["DB_ENCODING"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_NAME"] %>
  schema_search_path: <%= ENV["DB_SEARCH_PATH"] %>

development:
  <<: *default
  template: template0

staging:
  <<: *default

test:
  <<: *default
  host: <%= ENV["TEST_DB_HOST"] %>
  username: <%= ENV["TEST_DB_USERNAME"] %>
  password: <%= ENV["TEST_DB_PASSWORD"] %>
  database: <%= ENV["TEST_DB_NAME"] %>
  template: template0

production:
  <<: *default
